import os

def format_output(result_data, task_type, 
                  provider_used="unknown"):

    task_type = str(task_type).lower().strip()

    # Handle None result
    if result_data is None:
        return {
            "type": "text",
            "content": "Sorry, task failed across all providers.",
            "file_path": None,
            "caption": "",
            "provider": provider_used
        }

    # IMAGE result
    if task_type == "image_gen":
        # result_data is a dict with file_path and provider
        if isinstance(result_data, dict):
            fp = result_data.get("file_path", None)
            prov = result_data.get("provider", provider_used)
        else:
            fp = None
            prov = provider_used

        # Verify file actually exists
        if fp and os.path.exists(fp):
            return {
                "type": "image",
                "content": "",
                "file_path": fp,
                "caption": f"Generated by {prov}",
                "provider": prov
            }
        else:
            return {
                "type": "text",
                "content": "Image was generated but file not found.",
                "file_path": None,
                "caption": "",
                "provider": prov
            }

    # AUDIO result
    if task_type == "voice_out":
        if isinstance(result_data, str) and \
           os.path.exists(result_data):
            return {
                "type": "audio",
                "content": "",
                "file_path": result_data,
                "caption": f"Generated by {provider_used}",
                "provider": provider_used
            }
        else:
            return {
                "type": "text",
                "content": str(result_data) \
                    if result_data else "Audio failed.",
                "file_path": None,
                "caption": "",
                "provider": provider_used
            }

    # TEXT result (all other task types)
    if isinstance(result_data, dict):
        content = result_data.get("content") or \
                  result_data.get("result") or \
                  result_data.get("text") or \
                  str(result_data)
    else:
        content = str(result_data) if result_data else \
                  "No response received."

    return {
        "type": "text",
        "content": content,
        "file_path": None,
        "caption": f"Generated by {provider_used}",
        "provider": provider_used
    }
