def format_output(result_data, task_type, provider_used):
    """
    result_data can be:
    - a string (text generation)
    - a dict with 'path' (image/audio)
    """
    out = {
        "type": "text",
        "content": "",
        "file_path": None,
        "caption": "",
        "provider": provider_used
    }
    
    if task_type in ["IMAGE_GEN"]:
        out["type"] = "image"
        if isinstance(result_data, dict):
            out["file_path"] = result_data.get("path")
            out["caption"] = f"Generated by {provider_used}"
    elif task_type in ["VOICE_OUT"]:
        out["type"] = "audio"
        if isinstance(result_data, dict):
            out["file_path"] = result_data.get("path")
            out["caption"] = f"Generated by {provider_used}"
    else:
        out["type"] = "text"
        text = str(result_data)
        # clean up markdown if needed (very basic)
        out["content"] = text + f"\n\n_Generated by {provider_used}_"
        
    return out
